import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Button from './components/Button';
import Chart from './components/Chart';
import Search from './components/Search';
import SideNavigation from './components/SideNavigation';

const Home: NextPage = () => {
  
  const dummyData = [
    {
      title: 'Average response Time',
      avgResponseTime: 1800000,
      responseTime: 5400000,
      dataset: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
        pointStyle: 'circle',
        datasets: [
          {
            label: '',
            data: [10, 20, 15, 10, 50, 40, 30, 40],
            borderColor: '#F05D23',
            backgroundColor: '#ffffff',
          },
        ],
      },
    },
    {
      title: 'Replies per resolution',
      avgResponseTime: 1800000,
      responseTime: 5400000,
      dataset: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
        pointStyle: 'circle',
        datasets: [
          {
            label: '',
            data: [10, 20, 15, 10, 50, 40, 30, 40],
            borderColor: '#3E68FF',
            backgroundColor: '#ffffff',
          },
        ],
      },
    },
    {
      title: 'Average resolution time',
      avgResponseTime: 1800000,
      responseTime: 5400000,
      dataset: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
        pointStyle: 'circle',
        datasets: [
          {
            label: '',
            data: [10, 20, 15, 10, 50, 40, 30, 40],
            borderColor: '#FB6491',
            backgroundColor: '#ffffff',
          },
        ],
      },
    },
    {
      title: 'First contact resolution rate',
      avgResponseTime: 1800000,
      responseTime: 5400000,
      dataset: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
        pointStyle: 'circle',
        datasets: [
          {
            label: '',
            data: [10, 20, 15, 10, 50, 40, 30, 40],
            borderColor: '#07C9E2',
            backgroundColor: '#ffffff',
          },
        ],
      },
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Metacare</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link type='font' href='/gellion-regular.ttf' />
      </Head>
      <div className='flex font-gellion'>
        <menu className='md:flex w-2/5 md:w-1/4  bg-white border-r hidden'>
          <div className='px-2 py-10 w-full'>
            <div className='flex flex-col border border-[#ECEBF5] rounded-lg pl-16 py-4 pr-4 mr-3'>
              <h1 className='text-black font-bold'>Metacare</h1>
              <span className='text-[#696D8C] text-xs'>
                adeyinka@metacare.app
              </span>
            </div>
            <SideNavigation />
          </div>
        </menu>
        <aside className='min-h-screen w-full bg-white'>
          <nav className='flex items-center justify-between px-10 bg-white py-6 border-b border-[#ECEBF5]'>
            <Search />

            <div className='flex items-center border border-1 border-[#ECEBF5] rounded-lg py-3 px-4  flex-row ml-4 justify-between w-36'>
              <div className='flex border-r border-[#ECEBF5] pr-3 items-center'>
                <svg
                  className='mr-1'
                  width='14'
                  height='17'
                  viewBox='0 0 14 17'
                  fill='none'
                  xmlns='http://www.w3.org/2000/svg'>
                  <path
                    fillRule='evenodd'
                    clipRule='evenodd'
                    d='M9.23503 2.48071C9.10196 1.36502 8.15249 0.5 7.00098 0.5C5.84947 0.5 4.9 1.36502 4.76693 2.48071C2.88993 3.3316 1.58431 5.22166 1.58431 7.41667V11.1799L0.331437 13.662C0.0796442 14.1609 0.442195 14.75 1.00098 14.75H4.87901C5.18788 15.6239 6.02131 16.25 7.00098 16.25C7.98064 16.25 8.81407 15.6239 9.12295 14.75H13.001C13.5598 14.75 13.9223 14.1609 13.6705 13.662L12.4176 11.1799V7.41667C12.4176 5.22166 11.112 3.3316 9.23503 2.48071ZM10.9981 11.6964L11.7823 13.25H2.21967L3.00385 11.6964C3.05675 11.5916 3.08431 11.4759 3.08431 11.3585V7.41667C3.08431 5.25355 4.83786 3.5 7.00098 3.5C9.16409 3.5 10.9176 5.25355 10.9176 7.41667V11.3585C10.9176 11.4759 10.9452 11.5916 10.9981 11.6964Z'
                    fill='#A3A3C2'
                  />
                </svg>
                <span className='bg-[#F25A68] rounded h-4 w-4 mr-2 text-xs text-white items-center justify-center text-center'>
                  3
                </span>
              </div>
              <div className='flex items-center'>
                <div className='w-6 rounded-full mr-2 h-6 border border-[#6837EF]'></div>

                <svg
                  width='8'
                  height='7'
                  viewBox='0 0 12 7'
                  fill='none'
                  xmlns='http://www.w3.org/2000/svg'>
                  <path
                    fillRule='evenodd'
                    clipRule='evenodd'
                    d='M6 4.58579L10.2929 0.292893C10.6834 -0.0976311 11.3166 -0.0976311 11.7071 0.292893C12.0976 0.683418 12.0976 1.31658 11.7071 1.70711L6.70711 6.70711C6.31658 7.09763 5.68342 7.09763 5.29289 6.70711L0.292893 1.70711C-0.0976311 1.31658 -0.0976311 0.683418 0.292893 0.292893C0.683418 -0.0976311 1.31658 -0.0976311 1.70711 0.292893L6 4.58579Z'
                    fill='#696D8C'
                  />
                </svg>
              </div>
            </div>
          </nav>

          <menu className='flex items-center px-10 bg-white pt-6 border-b border-[#ECEBF5]'>
            <ul className='flex items-center'>
              <li className='cursor-pointer hover:text-[#414455] duration-150 text-[#060213] text-base border-b-2 border-[#6837EF] pb-6 mr-10'>
                Efficiency
              </li>
              <li className='cursor-pointer hover:text-[#414455] duration-150 text-[#696D8C] text-base pb-6 mr-10'>
                Volume
              </li>
              <li className='cursor-pointer hover:text-[#414455] duration-150 text-[#696D8C] text-base pb-6 mr-10'>
                Customer Satisfaction
              </li>
              <li className='cursor-pointer hover:text-[#414455] duration-150 text-[#696D8C] text-base pb-6 mr-10'>
                Blacklog
              </li>
            </ul>
          </menu>

          <div className='px-10'>
            <div className='flex flex-row mt-8 mb-3 items-center justify-between'>
              <h1 className='text-3xl'>Efficiency Analysis</h1>

              <div className='flex flex-row justify-between'>
                <div className='flex items-center border border-[#ECEBF5] bg-white px-4 py-2 rounded-md space-x-3 w-72 max-w-md mr-6'>
                  <svg
                    width='21'
                    height='21'
                    viewBox='0 0 21 21'
                    fill='none'
                    xmlns='http://www.w3.org/2000/svg'>
                    <path
                      d='M9.625 16.625C13.491 16.625 16.625 13.491 16.625 9.625C16.625 5.759 13.491 2.625 9.625 2.625C5.759 2.625 2.625 5.759 2.625 9.625C2.625 13.491 5.759 16.625 9.625 16.625Z'
                      stroke='#A3A3C2'
                      strokeWidth='2'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                    />
                    <path
                      d='M18.375 18.375L14.5687 14.5687'
                      stroke='#A3A3C2'
                      strokeWidth='2'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                    />
                  </svg>
                  <input
                    type='text'
                    placeholder='Search'
                    className='bg-white outline-none w-full text-sm rounded-lg py-2'
                  />
                </div>
                <div className='flex pr-6 border-r border-[#ECEBF5]'>
                  <Button
                    customStyle='flex justify-between w-48 items-center py-3 px-6 bg-white font-base text-black rounded-lg border border-[#ECEBF5]'
                    id='filter-select'>
                    <span className='font-base'>Filter Options</span>
                    <svg
                      width='12'
                      height='7'
                      viewBox='0 0 12 7'
                      fill='none'
                      xmlns='http://www.w3.org/2000/svg'>
                      <path
                        fillRule='evenodd'
                        clipRule='evenodd'
                        d='M6 4.58579L10.2929 0.292893C10.6834 -0.0976311 11.3166 -0.0976311 11.7071 0.292893C12.0976 0.683418 12.0976 1.31658 11.7071 1.70711L6.70711 6.70711C6.31658 7.09763 5.68342 7.09763 5.29289 6.70711L0.292893 1.70711C-0.0976311 1.31658 -0.0976311 0.683418 0.292893 0.292893C0.683418 -0.0976311 1.31658 -0.0976311 1.70711 0.292893L6 4.58579Z'
                        fill='#000000'
                      />
                    </svg>
                  </Button>
                </div>

                <div className='flex pl-6'>
                  <Button
                    customStyle='flex items-center py-3 px-6 bg-[#25BB87] font-base text-white rounded-lg'
                    id='export-button'>
                    Export
                  </Button>
                </div>
              </div>
            </div>

            {dummyData && dummyData.map((item, key)=>{
              return (
                <div className='md:flex  space-y-3 md:space-y-0 md:space-x-4 mt-6' key={key}>
                  <Chart data={item} />
                </div>
              );
            })}
            

          </div>
        </aside>
      </div>
    </div>
  );
};

export default Home;
